### ISSUE TITLE
rename

### ISSUE THREAD

**Issue by gusunavarro** [Daniel-KM/SubjectBrowse#1]
Hello
Today I install the plugin, rename subject browse to folder reference, but said that is not valid plugin.
thanks
gus

**Comment by Daniel-KM** [comment]
Hi,

When you load a zip from github, you should rename the plugin folder "Reference", not "Reference-master".

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by gusunavarro** [comment]
thanks very much
my problem was , that I am use the plugin from omeka and not from github..
thanks
gus

2016-05-29 3:17 GMT-03:00 Daniel Berthereau notifications@github.com:
