### ISSUE TITLE
Rerouting when there's only one element chosen (f.i.: Subject)

### ISSUE THREAD

**Issue by DBinaghi** [Daniel-KM/SubjectBrowse#10]
Hi.
I've just done some improvements to my fork of this plugin, and I've been thinking about a special case, when the plugin is used to offer a list/tree of just one metadata element: in that case, instead of having menu names "reference", opening another page from which to reach the element (say, **Subject**), it could be useful if menu was already showing a direct link to that element (so, **Subject** and **Browse by Subject**, instead of **Reference** and **Browse by Reference**). 
What do you think, could it be a good idea? Should the routing system be changed, or what?
Thanks.

**Comment by Daniel-KM** [comment]
The partial may be changed to load the later one directly.

**Comment by DBinaghi** [comment]
I think the biggest issue here is the main navigation bar: no matter what I use as a label (say: **Subject**), via `filterPublicNavigationMain`, it will always show the one that's set under `/admin/appearance/edit-navigation` (i.e. **Reference**).

Do you know a way to overwrite labels of the main navigation bar programmaticaly, by any chance?

**Comment by DBinaghi** [comment]
Solved. Please see my pull request and commits for that and some other improvements.
