### ISSUE TITLE
This is not a valid plugin

### ISSUE THREAD

**Issue by cem1kilic** [Daniel-KM/SubjectBrowse#2]
Hi, I uncompressed the following file
http://omeka.org/wordpress/wp-content/uploads/Reference-2.4.1.zip
into plugin folder. The name of the plugin is Reference'.
But on Omeka admin plugin page, I got the following error next to Reference plugin.
"This is not a valid plugin".
All other plugins work fine. I am using Omeka 2.4.1 on LAMP. 
Thanks

**Comment by Daniel-KM** [comment]
Hi,

I just checked it and it works fine. Probably related to rights (set 755/644).

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
