### ISSUE TITLE
When reference_query_type=contains the reference list counts are incorrect

### ISSUE THREAD

**Issue by adehner** [Daniel-KM/SubjectBrowse#3]
I have several subject values that are wrapped in the html tag <em></em>. When my reference_query_type was set to "is exactly", the reference list links were not matching these formatted subjects. 

I changed the reference_query_type to "contains". Now I am catching all of the subjects, this is progress. But the counts which display in the list of references are incorrect. The number displaying with each reference link does not match the number of results that are returned when the link is clicked.

**Comment by adehner** [comment]
Ideally, I would like to keep the "is exactly" query type. Ideally the counts and queries would ignore html formatting and the links would return formatted subjects along with plain text subjects. It would be wonderful if the plugin could accommodate this.

**Comment by Daniel-KM** [comment]
Hi,

In Dublin Core, this is not recommended to have formatted text, except in fields like DC:Description. So here, a subject "`My Subject`" is not the same than "`<p>My Subject</p>`".

About the count, this looks strange, but it may be related to public/reserved items.

These are new features, so I'll implement them when I'll have some time (or some credit). 

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by adehner** [comment]
Thanks, good point about DC best practices. I stripped the html tags and and the problem is resolved for me.
