### ISSUE TITLE
Restrict reference to one collection?

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/SubjectBrowse#5]
Is it possible to restrict results of reference to one collection?

For example, I would like to print the results for "/references/item-type-metadata-country" (so a list of countries) but only for the items appearing in collection A.

**Comment by Daniel-KM** [comment]
In fact, this is possible (and many more) in the version for Omeka S, but not for Omeka Classic.

So if you really need it, you can modify or extend the helper `Reference_View_Helper_Reference` for the method [`_getReferencesList()`](https://github.com/Daniel-KM/Omeka-plugin-Reference/blob/master/views/helpers/Reference.php#L290) with this line:

```php
            $select->where('items.collection_id = ' . (int) $collectionId);
```
The same for the method `_count()`.

Pass the collectionId to the method too, or hard code it.
